# -*- coding: utf-8 -*-
"""Resp_t9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK_2bNYtgBrH6dY5wJGy5pCApInsdPcV

aulas dos primeiros scrips
"""

nome = input("Digite seu nome completo:")

quantidade_caracteres = len(nome)

primeira_letra = nome[0]

ultima_letra = nome[-1]

nome_maiusculo = nome.upper()


print(f"nome digitado: {nome}")
print(f"quantidade de caracteres: {quantidade_caracteres}")
print(f"primeira letra: {primeira_letra}")
print(f"ultima letra: {ultima_letra}")
print(f"nome em maisculas: {nome_maiusculo}")

# Lendo texto (sempre retorna string)
nome = input("Digite seu nome: ")

# Lendo número inteiro
idade = int(input("Digite sua idade: "))

# Lendo número real
cidade = input("Digite sua cidade: ")

print(f"Olá {nome}, você tem {idade} anos e mora em {cidade}  Seja bem-vindo(a) ao Python!.")